version: '3.7'

services:
  db:
    image: postgres:13.10
    environment:
      POSTGRES_PASSWORD: tracking_password
      POSTGRES_DB: tracking
      POSTGRES_USER: tracking_user
    ports:
      - "5433:5432"
    volumes:
      - "pg_kdata:/var/lib/postgresql/data"

  # backend:
  #   build:
  #     context: .
  #     dockerfile: ./deploy/Dockerfile
  #   env_file: 
  #     - ./.env
  #   ports:
  #     - "8000:8000"
  #   container_name: backend_api
  #   command: ./manage.py runserver 0.0.0.0:8000
  #   restart: unless-stopped

volumes:
  db-volume:
  pg_kdata:
