version: '3'

volumes:
  pg_kdata:

services:
  db:
    image: postgres:13.10
    environment:
      POSTGRES_PASSWORD: tracking_password
      POSTGRES_DB: tracking
      POSTGRES_USER: tracking_user
    ports:
      - 5432:5432
    volumes:
      - pg_kdata:/var/lib/postgresql/data

  backend:
    build: 
        dockerfile: ./deploy/
# Dockerfile:
    env_file: 
      - ~/DEV/habits_tracking/.env
    ports:
      - "8000:8000"
    container_name: backend_api
    command: bash ./start-django-dev.sh
    restart: unless-stopped

